name: Cleanup old package versions

on:
  push:
    branches: ['main']
  workflow_dispatch:  # 允许手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/delete-package-versions@v5
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: 'queue-bridge-node'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'